server:
  port: 1857

spring:
  application:
    name: service-gateway
  profiles:
    active: dev
  cloud:
    gateway:
      default-filters:
      - name: Hystrix
        args:
          name: fallbackcmd
          fallbackUri: forward:/fallbackcontroller
      discovery:
        locator:
          enabled: false
          lowerCaseServiceId: true
      routes:
        - id: service-b
          uri: lb://service-b
          predicates:
            - Path=/b/**
          filters:
          - StripPrefix=1

        - id: service-feign
          uri: lb://service-feign
          predicates:
          - Path=/feign/**
          filters:
          - StripPrefix=1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000

eureka:
  instance:
    instance-id: ${eureka.instance.hostname}:${server.port}[${spring.cloud.client.ip-address}]
    hostname: service-gateway

eureka-server:
  port: 8013


---
spring:
  profiles: dev

eureka:
  client:
    service-url:
      defaultZone: http://localhost:${eureka-server.port}/eureka/
  instance:
    hostname: localhost



---
spring:
  profiles: qa

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:${eureka-server.port}/eureka/
