eureka:
  server:
    enable-self-preservation: false
  instance:
    instance-id: ${eureka.instance.hostname}:${server.port}[${spring.cloud.client.ip-address}]
    hostname: eureka-server

spring:
  application:
    name: eureka-server
  profiles:
    active: dev

server:
  port: 8013


---
spring:
  profiles: dev

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/


---
spring:
  profiles: qa

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://eureka-server1:${server.port}/eureka/
